"""What each threat class *is*, for the questions the alert store cannot answer.

Retrieval answers "how many", "which host", "when". It cannot answer "what is a
DGA and why does it matter", because that is not a fact about any row - it is
background an analyst is assumed to have and a judge watching the demo is not.
This module is that background, and nothing else.

Three rules govern what may be written here, and the tests enforce all three.

**Keyed on the frozen enum.** The keys are the exact ``threat_class`` values
from ``backend/app/schemas/enums.py::ThreatClass``. A class with no entry falls
back to live retrieval alone rather than to a guess, and ``test_knowledge.py``
fails if the two vocabularies ever drift apart.

**Evidence fields are the real ones.** Every name in ``evidence_fields``
appears in ``backend/fixtures/sample_by_class.json`` for that class. They are
what the detector actually emits, so an analyst reading "look at
``interval_cv``" can go and look at ``interval_cv``.

**No measurements.** Not one sentence here carries a threshold, a rate, a
duration or a count. That is not a style preference - it is what keeps the
verifier honest. ``grounding.unsupported_numbers()`` builds its allowed set
from every figure in the fact sheet, so a line here reading "beacons typically
every sixty seconds" would license the model to state sixty as though something
had measured it. Every number in an answer must come from a stored field, so
every number stays out of this file. MITRE technique ids are the one exception:
they are identifiers, not measurements, and the model may repeat one precisely
because the sheet asserted it.
"""

from __future__ import annotations

from dataclasses import dataclass

__all__ = ["ThreatKnowledge", "KNOWLEDGE", "lookup"]


@dataclass(frozen=True, slots=True)
class ThreatKnowledge:
    """Reference material for one threat class.

    The fields are ordered the way an analyst reads them: what it is, what the
    attacker gets out of it, where to look, what it maps to, and - the one most
    often missing from a console - what benign traffic looks the same.
    """

    label: str
    #: One sentence: what the behaviour is, in the words an operator would use.
    summary: str
    #: Why an attacker does this, and what it buys them.
    intent: str
    #: How the detection layer recognises it, qualitatively.
    detection: str
    #: Evidence keys carrying the signal, in the order worth reading them.
    evidence_fields: tuple[str, ...]
    #: MITRE ATT&CK technique ids, matching what the detectors put on the alert.
    mitre: tuple[str, ...]
    #: What an analyst should establish next. Never an instruction to act on
    #: traffic: this system cannot send anything toward the monitored network,
    #: so "block it" would be a false statement about the product.
    investigate: str
    #: Legitimate traffic that produces the same shape. The single most useful
    #: line on a console that fires on behaviour rather than signatures.
    benign_lookalike: str


KNOWLEDGE: dict[str, ThreatKnowledge] = {
    "dga_domain": ThreatKnowledge(
        label="DGA Domain",
        summary=(
            "A host is resolving domain names that were generated by an "
            "algorithm rather than chosen by a person."
        ),
        intent=(
            "Malware that hardcodes one command-and-control address dies when "
            "that address is taken down. A domain generation algorithm has the "
            "implant and its operator derive the same changing list of names "
            "from a shared seed, so the operator need only register a few of "
            "them and the implant finds the live one by trying the rest."
        ),
        detection=(
            "Algorithmic names do not look like human ones. They carry higher "
            "character entropy, longer consonant runs, more digits and worse "
            "n-gram scores against ordinary language, and because most of the "
            "generated list was never registered, the host collects failed "
            "lookups while it hunts for the one that resolves."
        ),
        evidence_fields=(
            "query_entropy",
            "ngram_score",
            "nxdomain_rate",
            "nxdomain_count",
            "consonant_run",
            "digit_ratio",
            "query_length",
            "label_count",
        ),
        mitre=("T1568.002",),
        investigate=(
            "Establish which process on the source host is issuing the "
            "lookups, whether any generated name resolved rather than failed, "
            "and whether the same host also shows beaconing - a DGA that found "
            "its answer becomes a periodic callback, and the two alerts "
            "together are a far stronger claim than either alone."
        ),
        benign_lookalike=(
            "Content delivery networks, telemetry endpoints and antivirus "
            "reputation services all use machine-generated hostnames, and a "
            "misconfigured DNS suffix search list manufactures failed lookups "
            "in bulk without any malware involved."
        ),
    ),
    "dns_tunnelling": ThreatKnowledge(
        label="DNS Tunnelling",
        summary=(
            "A host is carrying data inside DNS queries and answers rather "
            "than using DNS to look names up."
        ),
        intent=(
            "DNS is the one protocol almost every network resolves outward "
            "even where nothing else is allowed, and it is rarely inspected as "
            "closely as web traffic. Encoding payload into subdomain labels "
            "and reading replies back out of records gives an operator a "
            "channel through egress controls that stop everything else."
        ),
        detection=(
            "Tunnelled traffic inverts the ordinary shape of DNS. Queries grow "
            "long and high-entropy because they are carrying encoded bytes, "
            "one parent domain accumulates far more distinct subdomains than a "
            "real service needs, the query rate to it stays high, and record "
            "types suited to carrying data are over-represented."
        ),
        evidence_fields=(
            "subdomain_entropy",
            "unique_subdomains",
            "query_length",
            "queries_per_sec",
            "txt_ratio",
            "parent_domain",
            "record_type",
        ),
        mitre=("T1071.004",),
        investigate=(
            "Identify the parent domain and who registered it, establish "
            "whether the traffic is bidirectional or only outbound, and check "
            "whether the same host also shows an exfiltration alert - the "
            "volume moved through a tunnel is what turns a channel into a loss."
        ),
        benign_lookalike=(
            "Some antivirus and reputation products genuinely encode lookups "
            "into subdomains, and captive-portal checks and certain "
            "cloud-service health probes produce long, varied, high-rate "
            "queries under a single parent domain as designed."
        ),
    ),
    "c2_beaconing": ThreatKnowledge(
        label="Beaconing",
        summary=(
            "A host is contacting the same destination on a regular cadence, "
            "the way a program does and a person does not."
        ),
        intent=(
            "An implant that has landed needs to ask for instructions without "
            "keeping a connection open that would stand out. It checks in on "
            "an interval instead, and the interval is the tell: the timing is "
            "machine-regular where human-driven traffic is bursty and "
            "irregular."
        ),
        detection=(
            "The detector measures the intervals between connections to one "
            "destination rather than their content, which is why this works on "
            "fully encrypted traffic. Low variation in those intervals, a "
            "strong autocorrelation peak, repetitive payload sizes and a "
            "destination this host returns to and little else are the signal. "
            "Deliberate jitter widens the spread but rarely erases the "
            "periodicity underneath."
        ),
        evidence_fields=(
            "interval_cv",
            "periodicity_score",
            "autocorrelation_peak",
            "mean_interval_sec",
            "jitter_pct",
            "observed_periods",
            "destination_repetition",
            "payload_size_cv",
        ),
        mitre=("T1071",),
        investigate=(
            "Establish what the destination is and whether the organisation "
            "has any reason to talk to it, how long the cadence has been "
            "running, and which other hosts contact the same destination - "
            "beaconing from several hosts at once is a deployment, not an "
            "anomaly. Check the source host for a preceding DGA or scan alert."
        ),
        benign_lookalike=(
            "Software update checks, monitoring agents, NTP, mail polling and "
            "metrics push are all periodic by design, and a well-behaved "
            "enterprise agent looks almost exactly like a well-written implant "
            "at the timing layer. The destination, not the cadence, is what "
            "separates them."
        ),
    ),
    "encrypted_malware": ThreatKnowledge(
        label="Encrypted-Session Malware",
        summary=(
            "A TLS session whose handshake characteristics do not match the "
            "software this network normally runs."
        ),
        intent=(
            "Encrypting the channel hides the payload from inspection, and "
            "that is exactly what an operator wants. It does not hide how the "
            "client negotiated the session, and malware families are usually "
            "built on TLS stacks that differ from the browsers and agents "
            "around them."
        ),
        detection=(
            "A JA3 or JA4 fingerprint summarises the client's handshake - the "
            "cipher suites it offered, the extensions and the order it put "
            "them in - into one hash, without decrypting anything. A "
            "fingerprint that is rare on this network, new for this host, or "
            "matches a known family stands out. Self-signed certificates, "
            "unusually short certificate validity and a high-entropy or absent "
            "server name add to the picture."
        ),
        evidence_fields=(
            "ja3",
            "ja3_rarity",
            "ja3_novel_for_host",
            "ja3_frequency",
            "matched_family",
            "self_signed",
            "cert_validity_days",
            "sni",
            "sni_entropy",
            "ssl_version",
        ),
        mitre=("T1071.001",),
        investigate=(
            "Establish which application on the host owns that fingerprint and "
            "whether it appeared for the first time recently, then check "
            "whether other hosts present the same one. No payload is available "
            "and none is needed: the claim is about the handshake."
        ),
        benign_lookalike=(
            "Any newly installed or updated application brings a fingerprint "
            "this network has not seen, and internal services legitimately run "
            "self-signed certificates. Rarity is a statement about this "
            "network's baseline, not about the software's intent."
        ),
    ),
    "port_scan": ThreatKnowledge(
        label="Port Scanning",
        summary=(
            "One source is probing many ports or many addresses in a short "
            "span, most of the attempts going nowhere."
        ),
        intent=(
            "Before anything can be attacked it has to be found. Scanning maps "
            "which addresses answer and which services they run, and it is "
            "normally the earliest stage of an intrusion that is visible from "
            "the network at all - which makes it the most valuable alert to "
            "correlate forward from."
        ),
        detection=(
            "The shape is fan-out with a poor success rate: a single source "
            "reaching a large spread of destination ports or destination "
            "addresses inside one window, with most connections refused or "
            "never completing the handshake. The ratio of unanswered SYNs to "
            "established sessions separates a scan from ordinary client "
            "traffic."
        ),
        evidence_fields=(
            "unique_dst_ports",
            "unique_dst_ips",
            "syn_no_ack_ratio",
            "connection_attempts",
            "rejected_connections",
            "window_seconds",
        ),
        mitre=("T1046",),
        investigate=(
            "Establish whether the source is internal or external, whether the "
            "spread is vertical - many ports on one host - or horizontal - one "
            "port across many hosts, and which probes were answered. An "
            "internal source scanning internally is lateral movement and "
            "deserves the strongest reading; check the same host for later "
            "beaconing or exfiltration alerts."
        ),
        benign_lookalike=(
            "Vulnerability scanners, asset inventory tools, network monitoring "
            "and service discovery all scan as their function, and a "
            "load-balancer health check across a service fleet produces the "
            "same fan-out. Whether the scanner is authorised is an "
            "organisational fact, not one visible in the traffic."
        ),
    ),
    "ddos": ThreatKnowledge(
        label="DDoS Flood",
        summary=(
            "Traffic volume toward a target far above its learned normal, "
            "typically from many sources at once."
        ),
        intent=(
            "The aim is exhaustion rather than access - of bandwidth, of "
            "connection state, or of the service's capacity to answer. It is "
            "terminal impact rather than a step toward anything else, which is "
            "why it sorts last in the kill chain."
        ),
        detection=(
            "Rate against baseline is the primary signal: packets, flows and "
            "bytes per second measured against the band this target normally "
            "occupies. Source address entropy separates a distributed flood "
            "from a single noisy host, and a high proportion of unanswered "
            "handshakes distinguishes state exhaustion from a genuine surge in "
            "real users."
        ),
        evidence_fields=(
            "packets_per_sec",
            "flows_per_sec",
            "bytes_per_sec",
            "baseline_band",
            "unique_sources",
            "source_ip_entropy",
            "syn_no_ack_ratio",
            "window_seconds",
        ),
        mitre=("T1498",),
        investigate=(
            "Establish whether the sources are spoofed or real, whether the "
            "traffic is amplified through a reflector, and whether the target "
            "was already under attack by another class - a flood is sometimes "
            "cover for activity elsewhere on the network. Note that this "
            "console observes; it cannot rate-limit or drop anything."
        ),
        benign_lookalike=(
            "A launch, a broadcast, a scheduled batch job or a backup window "
            "produces a genuine spike against baseline, and a "
            "misbehaving client in a retry loop looks like a small flood from "
            "one source."
        ),
    ),
    "data_exfiltration": ThreatKnowledge(
        label="Exfiltration",
        summary=(
            "A host is sending out substantially more than it normally sends, "
            "and more than it is receiving."
        ),
        intent=(
            "This is the stage where an intrusion becomes a loss. Everything "
            "before it is positioning; this is the data leaving, and it is the "
            "alert whose confirmation matters most."
        ),
        detection=(
            "Outbound volume is compared against what this host normally "
            "sends, not against a fixed number, so a busy server and a "
            "workstation are judged on their own baselines. A byte ratio "
            "heavily skewed outbound inverts the shape of ordinary client "
            "traffic, and transfers to destinations this host has never used "
            "before, or at hours it is never active, raise the reading."
        ),
        evidence_fields=(
            "outbound_bytes",
            "baseline_outbound_bytes",
            "baseline_ratio",
            "out_in_byte_ratio",
            "robust_z_score",
            "destination_rarity",
            "destination_novel",
            "time_of_day_deviation",
            "transfer_duration_sec",
        ),
        mitre=("T1048",),
        investigate=(
            "Establish what the destination is and whether the host has ever "
            "used it before, what the source host has access to, and whether "
            "an earlier alert on the same host explains how an operator got "
            "there. Exfiltration preceded by beaconing on the same host is a "
            "sequence, and the sequence is the argument."
        ),
        benign_lookalike=(
            "Cloud backup, large file sharing, video conferencing, a code "
            "push, a database replica and a scheduled off-site sync all move "
            "far more out than in. Novelty of the destination usually "
            "separates them better than the volume does."
        ),
    ),
}


def lookup(threat_class: str | None) -> ThreatKnowledge | None:
    """Reference material for *threat_class*, or ``None`` if we have none.

    ``None`` rather than a placeholder: an entry we do not have is answered
    from retrieved alerts alone, which is a smaller answer but a true one.
    """
    if not threat_class:
        return None
    return KNOWLEDGE.get(threat_class)
