#!/usr/bin/env python3
"""Re-derive DGAConfig.score_threshold against the populations that decide it.

    python tools/dga_threshold_sweep.py --model artifacts/dga_model.joblib

Why the training CLI's own sweep is not enough
----------------------------------------------
``detection_core.ml.dga.training`` prints a threshold sweep, and it is the
right sweep for the question it asks: precision and recall on the held-out
*test fold*. But the threshold is a **deployment** decision, and the test fold
is not the deployment. Three populations that decide whether an analyst trusts
the DGA panel are either absent from it or under-represented in it:

* **CDN / object-storage hostnames.** Now in the corpus, so they *are* in the
  test fold - but benign rows are shuffle-split, so every provider in test was
  also in training. The number that matters is an **unseen provider**, which by
  construction cannot come from this model's own test fold. Pass
  ``--holdout-model`` (a model trained with those providers excluded) to get it.
* **DNS-tunnel subdomains.** Not in the corpus at all, and not a DGA - they are
  ``dns_tunnelling``'s finding. Every one the DGA detector claims is an alert
  filed under the wrong threat class.
* **Ordinary registrable domains** far below the Tranco slice used in training.

So this sweeps the threshold across all of them at once and prints where each
population's score band sits, which is what "pick a threshold" actually means.

Nothing here selects a threshold automatically. It prints the curve and a
recommendation; the value lives in ``DGAConfig.score_threshold`` and changing
it is a detection-code edit for that file's owner.

SYNTHETIC/SAMPLED. The CDN and Tranco populations are real public data; the
tunnel population is generated by ``tools/synth_flows.py``. None of it is a
capture from the deployment network, so these are separation figures, not a
production false-positive rate.
"""
from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "detection"))

from detection_core.ml.dga.dataset import (  # noqa: E402
    LABEL_DGA,
    load_dataset,
    split_dataset,
)
from detection_core.ml.dga.model import DGAModel  # noqa: E402

DEFAULT_THRESHOLDS = [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95]

#: Providers a --holdout-model was trained without. Kept here so the report can
#: name them; the model itself is built by the caller.
DEFAULT_HOLDOUT = ("cloudfront.net", "cdn77.org", "digitaloceanspaces.com")


def tunnel_domains(n: int = 400, seed: int = 26145) -> list[str]:
    """The DNS-tunnel names ``tools/synth_flows.py`` puts on the wire."""
    rng = random.Random(seed)
    alphabet = "abcdefghijklmnopqrstuvwxyz0123456789"
    return [
        "".join(rng.choice(alphabet) for _ in range(48)) + ".t.exfil-channel.test"
        for _ in range(n)
    ]


def load_populations(
    dataset_csv: Path, cdn_eval: Path | None, tranco_eval: Path | None
) -> dict[str, dict[str, Any]]:
    """Each population: its domains, and whether a fire on it is right."""
    dataset = load_dataset(dataset_csv)
    split = split_dataset(dataset, test_size=0.25, random_state=42)
    held_out_dga = [
        d for d, y in zip(split.test_domains, split.test_labels) if y == LABEL_DGA
    ]

    pops: dict[str, dict[str, Any]] = {
        "dga_held_out_families": {
            "domains": held_out_dga,
            "positive": True,
            "note": "DGA families never seen in training - a fire here is a TRUE positive",
        },
        "dns_tunnel_subdomains": {
            "domains": tunnel_domains(),
            "positive": False,
            "note": "belongs to dns_tunnelling - a fire here is a MISFILED alert",
        },
    }
    if cdn_eval and cdn_eval.is_file():
        pops["cdn_same_provider"] = {
            "domains": [
                line.strip() for line in cdn_eval.read_text(encoding="utf-8").splitlines()
                if line.strip()
            ],
            "positive": False,
            "note": "real CDN hostnames, providers seen in training, hostnames not",
        }
    if tranco_eval and tranco_eval.is_file():
        pops["tranco_ordinary"] = {
            "domains": [
                line.strip() for line in tranco_eval.read_text(encoding="utf-8").splitlines()
                if line.strip()
            ],
            "positive": False,
            "note": "ordinary registrable domains, below the slice used in training",
        }
    return pops


def band(scores: list[float]) -> tuple[float, float, float, float]:
    ordered = sorted(scores)
    n = len(ordered)
    return (
        ordered[0],
        ordered[max(0, int(0.05 * n) - 1)],
        ordered[max(0, int(0.95 * n) - 1)],
        ordered[-1],
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--model", default=str(ROOT / "artifacts" / "dga_model.joblib"))
    ap.add_argument("--holdout-model", default=None,
                    help="model trained WITHOUT the providers in --holdout-suffixes, "
                         "used only to score the unseen-provider population")
    ap.add_argument("--holdout-domains", default=None,
                    help="newline-separated hostnames of the held-out providers")
    ap.add_argument("--dataset", default=str(
        ROOT / "detection" / "detection_core" / "ml" / "dga" / "data" / "dga_dataset.sample.csv"))
    ap.add_argument("--cdn-eval", default=None, help="newline-separated CDN eval hostnames")
    ap.add_argument("--tranco-eval", default=None, help="newline-separated ordinary domains")
    ap.add_argument("--thresholds", default=",".join(str(t) for t in DEFAULT_THRESHOLDS))
    ap.add_argument("-o", "--output", default=None)
    args = ap.parse_args()

    thresholds = [float(t) for t in args.thresholds.split(",") if t.strip()]
    model = DGAModel.load(Path(args.model))
    pops = load_populations(
        Path(args.dataset),
        Path(args.cdn_eval) if args.cdn_eval else None,
        Path(args.tranco_eval) if args.tranco_eval else None,
    )

    scored = {
        name: {**meta, "scores": model.predict_scores(meta["domains"])}
        for name, meta in pops.items()
        if meta["domains"]
    }

    if args.holdout_model and args.holdout_domains:
        hm = DGAModel.load(Path(args.holdout_model))
        domains = [
            line.strip()
            for line in Path(args.holdout_domains).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        scored["cdn_unseen_provider"] = {
            "domains": domains,
            "positive": False,
            "note": f"providers held out of training entirely ({', '.join(DEFAULT_HOLDOUT)}) "
                    f"- scored with --holdout-model",
            "scores": hm.predict_scores(domains),
        }

    print()
    print("SCORE BANDS PER POPULATION")
    print("=" * 104)
    print(f"{'population':26s} {'role':9s} {'n':>6s} {'min':>7s} {'p5':>7s} {'p95':>7s} {'max':>7s}   note")
    print("-" * 104)
    for name, meta in scored.items():
        lo, p5, p95, hi = band(meta["scores"])
        role = "POSITIVE" if meta["positive"] else "negative"
        print(f"{name:26s} {role:9s} {len(meta['scores']):6d} "
              f"{lo:7.3f} {p5:7.3f} {p95:7.3f} {hi:7.3f}   {meta['note'][:34]}")

    print()
    print("THRESHOLD SWEEP")
    print("=" * 104)
    neg_names = [n for n, m in scored.items() if not m["positive"]]
    header = f"{'thr':>5s} {'recall':>7s}"
    for n in neg_names:
        header += f" {n[:15]:>16s}"
    header += f" {'precision*':>11s}"
    print(header)
    print(f"{'':>5s} {'(DGA)':>7s}" + "".join(f" {'FP rate':>16s}" for _ in neg_names)
          + f" {'(all pops)':>11s}")
    print("-" * 104)

    rows = []
    pos = scored["dga_held_out_families"]["scores"]
    for thr in thresholds:
        tp = sum(1 for s in pos if s >= thr)
        recall = tp / len(pos)
        fps = {n: sum(1 for s in scored[n]["scores"] if s >= thr) for n in neg_names}
        total_fp = sum(fps.values())
        precision = tp / (tp + total_fp) if (tp + total_fp) else None
        line = f"{thr:5.2f} {recall:7.3f}"
        for n in neg_names:
            line += f" {fps[n] / len(scored[n]['scores']):16.4f}"
        line += f" {precision:11.4f}" if precision is not None else f" {'-':>11s}"
        print(line)
        rows.append({
            "threshold": thr, "recall": recall, "tp": tp,
            "fp_by_population": fps,
            "fp_rate_by_population": {
                n: fps[n] / len(scored[n]["scores"]) for n in neg_names
            },
            "precision_all_populations": precision,
        })

    print()
    print("* precision here pools every negative population at equal weight. It is a")
    print("  comparison aid across thresholds, NOT a deployment precision - the real")
    print("  mix of CDN vs ordinary vs tunnel traffic on a given network sets that.")

    payload = {
        "kind": "dga_operational_threshold_sweep",
        "model": str(args.model),
        "holdout_model": args.holdout_model,
        "populations": {
            n: {"n": len(m["scores"]), "positive": m["positive"], "note": m["note"],
                "band": band(m["scores"])}
            for n, m in scored.items()
        },
        "sweep": rows,
        "honesty_note": (
            "Real public data (Tranco, Umbrella) plus generated tunnel names. Not a "
            "capture from the deployment network; separation figures, not a production FPR."
        ),
    }
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        print(f"\n[+] -> {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
