"""Independent stdlib-only v9 structural oracle and explicit synthetic builder.

No Rust/PyO3 imports, no Rust output used for expectations. Default mode checks
existing bytes, SHA sidecars and frozen expected structures without writing.
--generate explicitly creates only the enumerated synthetic artifacts. Genuine
exporter captures are never generated by that mode. --describe prints structure.
"""

import argparse
import hashlib
import json
from pathlib import Path
import struct
import socket
import subprocess
import time

ROOT = Path(__file__).parent / "fixtures" / "export" / "netflow_v9"


def decode(blob):
    if len(blob) < 20:
        return {"error": "TruncatedHeader"}
    version, count, uptime, secs, seq, source = struct.unpack_from("!HHIIII", blob)
    if version != 9:
        return {"error": "UnsupportedVersion"}
    result = {"header": [version, count, uptime, secs, seq, source], "flowsets": []}
    offset = 20
    frames = []
    while offset < len(blob):
        if len(blob) - offset < 4:
            return {"error": "TrailingPacketBytes"}
        ident, length = struct.unpack_from("!HH", blob, offset)
        if length < 4:
            return {"error": "InvalidFlowSetLength"}
        if offset + length > len(blob):
            return {"error": "FlowSetBeyondPacket"}
        frames.append((ident, length, offset, blob[offset + 4:offset + length]))
        offset += length
    if not frames:
        return {"error": "MissingFlowSets"}
    templates = {}
    parsed = 0
    reliable = True
    stopped = False
    for ordinal, (ident, length, offset, payload) in enumerate(frames):
        fs = {"id": ident, "length": length, "offset": offset, "ordinal": ordinal,
              "raw": payload.hex(), "processed": not stopped}
        result["flowsets"].append(fs)
        if ident < 2:
            fs.update(kind="templates", records=[], padding="")
            pos = 0
            while pos < len(payload):
                rest = payload[pos:]
                if len(rest) <= 3:
                    fs["padding"] = rest.hex()
                    if any(rest):
                        reliable = False
                        stopped = True
                    break
                header_len = 4 if ident == 0 else 6
                tid = struct.unpack_from("!H", rest)[0]
                if len(rest) < header_len:
                    reliable = False
                    stopped = True
                    fs["records"].append({"id": tid, "ordinal": len(fs["records"]),
                                          "offset": offset + 4 + pos, "state": "Rejected",
                                          "scope": 0, "count": 0, "fields": [], "raw": rest.hex()})
                    break
                if ident == 0:
                    nfields = struct.unpack_from("!H", rest, 2)[0]
                    scope, descriptor_len, malformed = 0, nfields * 4, False
                else:
                    scope_len, option_len = struct.unpack_from("!HH", rest, 2)
                    scope = scope_len // 4
                    descriptor_len = scope_len + option_len
                    nfields = scope + option_len // 4
                    malformed = bool(scope_len % 4 or option_len % 4)
                extent = header_len + descriptor_len
                trusted = extent <= len(rest)
                fields = []
                if trusted and not malformed:
                    fields = [list(struct.unpack_from("!HH", rest, p))
                              for p in range(header_len, extent, 4)]
                supported = trusted and not malformed and tid >= 256 and 0 < nfields <= 256
                supported = supported and all(width > 0 for _, width in fields)
                supported = supported and 0 < sum(width for _, width in fields) <= 65531
                state = "Unprocessed" if stopped else "Applied" if supported else "Rejected"
                raw = rest[:extent] if trusted else rest
                rec = {"id": tid, "ordinal": len(fs["records"]), "offset": offset + 4 + pos,
                       "scope": scope, "count": nfields, "fields": fields, "state": state, "raw": raw.hex()}
                fs["records"].append(rec)
                if not stopped:
                    if supported:
                        templates[tid] = (ident, scope, fields)
                        parsed += 1
                    else:
                        reliable = False
                        if trusted and tid >= 256:
                            templates.pop(tid, None)
                        else:
                            stopped = True
                if not trusted:
                    break
                pos += extent
            if not fs["records"]:
                reliable = False
                stopped = True
        elif ident < 256:
            fs["kind"] = "reserved"
            if not stopped:
                reliable = False
        else:
            fs.update(kind="data", state="Unprocessed", records=[], padding="")
            if stopped:
                continue
            if ident not in templates:
                reliable = False
                fs["state"] = "SkippedUnknown"
                continue
            template_kind, scope, fields = templates[ident]
            width = sum(length for _, length in fields)
            nrecords, remainder = divmod(len(payload), width)
            padding = payload[nrecords * width:]
            fs["padding"] = padding.hex()
            if not nrecords or remainder > 3 or any(padding):
                reliable = False
                fs["state"] = "Rejected"
                continue
            fs["state"] = "Decoded"
            parsed += nrecords
            for record_ordinal in range(nrecords):
                raw = payload[record_ordinal * width:(record_ordinal + 1) * width]
                values = []
                field_offset = 0
                for field_ordinal, (field_id, field_width) in enumerate(fields):
                    role = "Data" if template_kind == 0 else "Scope" if field_ordinal < scope else "Option"
                    values.append([field_id, field_width, role, raw[field_offset:field_offset + field_width].hex()])
                    field_offset += field_width
                fs["records"].append({"ordinal": record_ordinal, "offset": offset + 4 + record_ordinal * width,
                                      "raw": raw.hex(), "fields": values})
    result["count"] = "Inconclusive" if not reliable else "Match" if count == parsed else "Mismatch"
    result["parsed_count"] = parsed if reliable else None
    result["reset"] = stopped
    return result


def frame(ident, payload):
    return struct.pack("!HH", ident, 4 + len(payload)) + payload


def template(ident, fields):
    return struct.pack("!HH", ident, len(fields)) + b"".join(struct.pack("!HH", *f) for f in fields)


def options(ident, scopes, fields):
    return struct.pack("!HHH", ident, len(scopes) * 4, len(fields) * 4) + b"".join(
        struct.pack("!HH", *f) for f in scopes + fields)


def packet(count, frames, *, source=42, seq=123, secs=100, uptime=9000):
    return struct.pack("!HHIIII", 9, count, uptime, secs, seq, source) + b"".join(frames)


def synthetic_cases():
    a = template(256, [(8, 4), (32769, 2), (8, 1)])
    b = template(256, [(999, 3)])
    return {
        "valid/ordinary": packet(3, [frame(0, a), frame(256, bytes.fromhex("01020304abcd0506070809cdef06"))]),
        "valid/options_positive": packet(2, [frame(1, options(300, [(1, 4)], [(48, 1), (49, 2)])), frame(300, b"\x01\x02\x03\x04\x05\x06\x07\0")]),
        "valid/options_zero_scope": packet(3, [frame(1, options(301, [], [(50, 1), (50, 2)])), frame(301, b"\x01\x02\x03\x04\x05\x06\0\0")]),
        "valid/options_scope_only": packet(2, [frame(1, options(302, [(2, 4)], [])), frame(302, b"\0\0\0\0")]),
        "valid/padding_three": packet(2, [frame(0, template(400, [(77, 5)])), frame(400, b"\x01\x02\x03\x04\x05\0\0\0")]),
        "valid/zero_record": packet(2, [frame(0, template(401, [(1, 2)])), frame(401, b"\0\0")], source=0, seq=0, uptime=0),
        "valid/max_header": packet(1, [frame(0, template(65535, [(65535, 4)]))], source=0xffffffff, seq=0xffffffff, secs=0xffffffff, uptime=0xffffffff),
        "stateful/redefinition": packet(4, [frame(0, a), frame(256, bytes(range(7))), frame(0, b), frame(256, b"abc")]),
        "stateful/data_before_template": packet(2, [frame(256, b"abc"), frame(0, b), frame(256, b"def")]),
        "stateful/rejected_replacement": packet(3, [frame(0, b), frame(256, b"abc"), frame(0, template(256, [(1, 0)])), frame(256, b"def")]),
        "stateful/reserved_order": packet(2, [frame(2, b"raw"), frame(0, b), frame(256, b"abc")]),
        "malformed/footer": packet(1, [frame(0, a)]) + b"\0",
        "malformed/length_three": packet(0, []) + struct.pack("!HH", 0, 3),
        "malformed/nonzero_padding": packet(2, [frame(0, template(400, [(1, 5)])), frame(400, b"abcde\x01")]),
        "malformed/untrusted_template_extent": packet(1, [frame(0, b"\x01\x00\0\x02\0\x01\0\x04")]),
        "malformed/empty_export": packet(0, []),
        "malformed/empty_template": packet(0, [frame(0, b"")]),
        "malformed/empty_options": packet(0, [frame(1, b"")]),
        "malformed/empty_data": packet(1, [frame(0, template(256, [(1, 4)])), frame(256, b"")]),
    }


def freeze_artifact(path, blob, provenance):
    """Explicit generation/capture mode only; refuse replacement of existing bytes."""
    digest = hashlib.sha256(blob).hexdigest()
    expected = {"sha256": digest, "provenance": provenance, "expected": decode(blob)}
    path.parent.mkdir(parents=True, exist_ok=True)
    for target, content in [(path, blob), (path.with_suffix(".sha256"), (digest + "\n").encode()),
                            (path.with_suffix(".json"), (json.dumps(expected, indent=2, sort_keys=True) + "\n").encode())]:
        if target.exists():
            if target.read_bytes() != content:
                raise ValueError(f"refusing to overwrite differing artifact: {target}")
        else:
            target.write_bytes(content)


def verify():
    paths = sorted(ROOT.rglob("*.bin"))
    if not paths:
        raise ValueError("no fixtures")
    for path in paths:
        blob = path.read_bytes()
        digest = hashlib.sha256(blob).hexdigest()
        expected = json.loads(path.with_suffix(".json").read_text())
        assert path.with_suffix(".sha256").read_text().strip() == digest, path
        assert expected["sha256"] == digest, path
        actual = decode(blob)
        assert expected["expected"] == actual, (path, actual, expected["expected"])
        print(f"PASS {path.relative_to(ROOT)} SHA/header/framing/layout/slices/padding/count")
    print(f"ORACLE PASS={len(paths)} FAIL=0 (independent Python stdlib)")


def capture_softflowd(executable, evidence_dir, commit, archive_sha, source_dir):
    """Test-only loopback collector; not a production/live ingestion API."""
    executable = executable.resolve(strict=True)
    pcap = Path(__file__).parent / "fixtures" / "pcap" / "m1d_synthetic.pcap"
    license_bytes = (source_dir / "LICENSE").read_bytes()
    version = subprocess.run([str(executable), "-h"], capture_output=True, text=True, check=False)
    receiver = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    receiver.bind(("127.0.0.1", 0))
    receiver.settimeout(0.2)
    port = receiver.getsockname()[1]
    command = [str(executable), "-d", "-r", str(pcap), "-v", "9", "-P", "udp", "-n", f"127.0.0.1:{port}"]
    producer = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    captures = []
    deadline = time.monotonic() + 30
    try:
        while time.monotonic() < deadline:
            try:
                blob, peer = receiver.recvfrom(65536)
                if peer[0] != "127.0.0.1":
                    raise ValueError("non-loopback exporter")
                captures.append(blob)
                if len(captures) > 64:
                    raise ValueError("bounded evidence capture exceeded 64 packets")
            except socket.timeout:
                if producer.poll() is not None:
                    break
        if producer.poll() is None:
            raise TimeoutError("softflowd did not terminate")
        stdout, stderr = producer.communicate(timeout=2)
        if producer.returncode != 0 or not captures:
            raise ValueError(f"exporter failed/no packets: rc={producer.returncode}; {stderr.decode(errors='replace')[:2000]}")
        print("PRODUCER_STDOUT", stdout.decode(errors="replace"))
        print("PRODUCER_STDERR", stderr.decode(errors="replace"))
        for ordinal, blob in enumerate(captures):
            decoded = decode(blob)
            if "error" in decoded or decoded["reset"]:
                raise ValueError(f"capture failed independent structural qualification: {decoded}")
            provenance = {"producer": "irino/softflowd", "commit": commit, "source_archive_sha256": archive_sha,
                          "source_url": f"https://github.com/irino/softflowd/tree/{commit}",
                          "license": "BSD-2-Clause plus bundled notices; see upstream LICENSE", "license_sha256": hashlib.sha256(license_bytes).hexdigest(),
                          "license_text": license_bytes.decode(), "version_help": (version.stdout + version.stderr),
                          "generation_command": command, "pcap_sha256": hashlib.sha256(pcap.read_bytes()).hexdigest(),
                          "capture_ordinal": ordinal, "sensitive_data": False,
                          "qualification": "raw loopback UDP from pinned independently built exporter, independent Python structural decode"}
            freeze_artifact(evidence_dir / f"softflowd_{ordinal:03}.bin", blob, provenance)
            print("CAPTURE", ordinal, len(blob), hashlib.sha256(blob).hexdigest(), decoded["count"])
    finally:
        receiver.close()
        if producer.poll() is None:
            producer.kill()
            producer.communicate()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--describe", type=Path)
    parser.add_argument("--capture-softflowd", type=Path)
    parser.add_argument("--evidence-dir", type=Path)
    parser.add_argument("--producer-commit")
    parser.add_argument("--archive-sha")
    parser.add_argument("--producer-source-dir", type=Path)
    args = parser.parse_args()
    if args.generate:
        for name, blob in synthetic_cases().items():
            freeze_artifact(ROOT / (name + ".bin"), blob,
                            {"producer": "independent Python struct/manual synthetic builder", "command":
                             "python ingestion/tests/netflow_v9_fixture_oracle.py --generate", "sensitive_data": False})
    if args.capture_softflowd:
        if not all([args.evidence_dir, args.producer_commit, args.archive_sha, args.producer_source_dir]):
            parser.error("capture requires evidence-dir, producer-commit, archive-sha and producer-source-dir")
        capture_softflowd(args.capture_softflowd, args.evidence_dir, args.producer_commit, args.archive_sha, args.producer_source_dir)
    elif args.describe:
        print(json.dumps(decode(args.describe.read_bytes()), indent=2, sort_keys=True))
    else:
        verify()


if __name__ == "__main__":
    main()
